/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import myDesign.*;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jp
 */
public class DesignSimstret extends javax.swing.JFrame {

    public Thread t = new Thread(new connect());

    /**
     * Creates new form DesignSim
     */
    public DesignSimstret() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        source.setVisible(true);
        A.setVisible(true);
        B.setVisible(true);
        C.setVisible(true);
        D.setVisible(true);
        E.setVisible(true);
        F.setVisible(true);
        Sink.setVisible(true);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        t.start();

    }

    public class connect implements Runnable {

        public void run() {
            try {
                // try {



                Thread.sleep(3500);
                jLabel2.setVisible(true);
                Thread.sleep(4500);

                jLabel3.setVisible(true);
                Thread.sleep(4700);
                jLabel4.setVisible(true);
                Thread.sleep(4900);
                jLabel5.setVisible(true);
                Thread.sleep(5100);
                jLabel6.setVisible(true);
                Thread.sleep(7800);

                jLabel1.setVisible(true);

            } catch (InterruptedException ex) {
                Logger.getLogger(DesignSimstret.class.getName()).log(Level.SEVERE, null, ex);
            }







        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        source = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        D = new javax.swing.JLabel();
        E = new javax.swing.JLabel();
        F = new javax.swing.JLabel();
        Sink = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 750));
        getContentPane().setLayout(null);

        source.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        source.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sourcepng.png"))); // NOI18N
        source.setText("Source");
        getContentPane().add(source);
        source.setBounds(770, 490, 170, 110);

        A.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Computer-icon.png"))); // NOI18N
        A.setText("A");
        getContentPane().add(A);
        A.setBounds(780, 230, 150, 130);

        B.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Computer-icon.png"))); // NOI18N
        B.setText("B");
        getContentPane().add(B);
        B.setBounds(750, 30, 140, 130);

        C.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Computer-icon.png"))); // NOI18N
        C.setText("C");
        getContentPane().add(C);
        C.setBounds(430, 20, 150, 130);

        D.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Computer-icon.png"))); // NOI18N
        D.setText("D");
        getContentPane().add(D);
        D.setBounds(260, 200, 150, 130);

        E.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Computer-icon.png"))); // NOI18N
        E.setText("E");
        getContentPane().add(E);
        E.setBounds(230, 470, 150, 130);

        F.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Computer-icon.png"))); // NOI18N
        F.setText("F");
        getContentPane().add(F);
        F.setBounds(530, 470, 150, 130);

        Sink.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        Sink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sinkpng.png"))); // NOI18N
        Sink.setText("Sink");
        getContentPane().add(Sink);
        Sink.setBounds(40, 350, 160, 110);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/left.gif"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(560, 50, 130, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/leftdown.gif"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 120, 140, 110);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/down.gif"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 350, 140, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/upside.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 490, 170, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/up.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(770, 370, 140, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/up.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(760, 150, 140, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesignSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesignSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesignSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesignSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesignSimstret().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel B;
    private javax.swing.JLabel C;
    private javax.swing.JLabel D;
    private javax.swing.JLabel E;
    private javax.swing.JLabel F;
    private javax.swing.JLabel Sink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel source;
    // End of variables declaration//GEN-END:variables
}
