/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package myDesign;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jp
 */
public class DesignSim extends javax.swing.JFrame {

    public Thread t = new Thread(new connect());
    
    /**
     * Creates new form DesignSim
     */
    public DesignSim() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        source.setVisible(false);
        A.setVisible(false);
        B.setVisible(false);
        C.setVisible(false);
        D.setVisible(false);
        E.setVisible(false);
        F.setVisible(false);
        Sink.setVisible(false);
        t.start();
       
    }

    public class connect implements Runnable{
        public void run(){
            try {
                source.setVisible(true);
                Thread.sleep(3500);
                
                A.setVisible(true);
                Thread.sleep(3500);
                
                B.setVisible(true);
                Thread.sleep(4500);
                
                C.setVisible(true);
                Thread.sleep(5500);
                
                D.setVisible(true);
                Thread.sleep(6500);
                
                E.setVisible(true);
                Thread.sleep(7500);
                
                F.setVisible(true);
                Thread.sleep(7500);
                
                Sink.setVisible(true);
                Thread.sleep(7500);
           
                
            } catch (InterruptedException ex) {
                Logger.getLogger(DesignSim.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        source = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        D = new javax.swing.JLabel();
        E = new javax.swing.JLabel();
        F = new javax.swing.JLabel();
        Sink = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 750));
        getContentPane().setLayout(null);

        source.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        source.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sourcepng.png"))); // NOI18N
        source.setText("Source");
        getContentPane().add(source);
        source.setBounds(770, 490, 170, 110);

        A.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Computer-icon.png"))); // NOI18N
        A.setText("A");
        getContentPane().add(A);
        A.setBounds(780, 230, 150, 130);

        B.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Computer-icon.png"))); // NOI18N
        B.setText("B");
        getContentPane().add(B);
        B.setBounds(750, 30, 140, 130);

        C.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Computer-icon.png"))); // NOI18N
        C.setText("C");
        getContentPane().add(C);
        C.setBounds(430, 20, 150, 130);

        D.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Computer-icon.png"))); // NOI18N
        D.setText("D");
        getContentPane().add(D);
        D.setBounds(260, 200, 150, 130);

        E.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Computer-icon.png"))); // NOI18N
        E.setText("E");
        getContentPane().add(E);
        E.setBounds(230, 470, 150, 130);

        F.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Computer-icon.png"))); // NOI18N
        F.setText("F");
        getContentPane().add(F);
        F.setBounds(530, 470, 150, 130);

        Sink.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        Sink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sinkpng.png"))); // NOI18N
        Sink.setText("Sink");
        getContentPane().add(Sink);
        Sink.setBounds(40, 350, 160, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesignSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesignSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesignSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesignSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesignSim().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel B;
    private javax.swing.JLabel C;
    private javax.swing.JLabel D;
    private javax.swing.JLabel E;
    private javax.swing.JLabel F;
    private javax.swing.JLabel Sink;
    private javax.swing.JLabel source;
    // End of variables declaration//GEN-END:variables
}
